// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SumCalculator.Data;

#nullable disable

namespace SumCalculator.Migrations
{
    [DbContext(typeof(ApplicatonDbContext))]
    partial class ApplicatonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SumCalculator.Models.CalculatorEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<decimal>("Sum")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18, 6)")
                        .HasColumnName("sum")
                        .HasComputedColumnSql("[value1] + [value2]", true);

                    b.Property<decimal?>("Value1")
                        .IsRequired()
                        .HasColumnType("decimal(18, 6)")
                        .HasColumnName("value1");

                    b.Property<decimal?>("Value2")
                        .IsRequired()
                        .HasColumnType("decimal(18, 6)")
                        .HasColumnName("value2");

                    b.HasKey("Id");

                    b.ToTable("calculation_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
